#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bin_dir="${KAN_SHIM_BIN_DIR:-$HOME/.local/bin}"
shim_path="$bin_dir/kan"
marker="Generated by simplekanban scripts/install-kan-shim.sh"

mkdir -p "$bin_dir"

if [[ -e "$shim_path" || -L "$shim_path" ]]; then
  if ! grep -q "$marker" "$shim_path" 2>/dev/null; then
    echo "refusing to overwrite existing kan: $shim_path" >&2
    echo "set KAN_SHIM_BIN_DIR to install somewhere else" >&2
    exit 1
  fi
fi

tmp="$(mktemp "${shim_path}.tmp.XXXXXX")"
cat > "$tmp" <<SHIM
#!/usr/bin/env bash
# $marker
set -euo pipefail

repo_root="$repo_root"
exec "\$repo_root/scripts/kan.sh" "\$@"
SHIM
chmod +x "$tmp"
mv "$tmp" "$shim_path"

echo "installed kan shim to $shim_path"

case ":$PATH:" in
  *":$bin_dir:"*) ;;
  *)
    echo "warning: $bin_dir is not on PATH" >&2
    echo "add this to your shell profile: export PATH=\"$bin_dir:\$PATH\"" >&2
    ;;
esac
